name = "Lean_RV64D_executable"
defaultTargets = ["LeanRV64DExecutable"]
moreLeanArgs = ["--tstack=400000"]

[[lean_lib]]
name = "LeanRV64DExecutable"
leanOptions.weak.linter.style.nameCheck = false

[[lean_exe]]
name = "run"
root = "LeanRV64DExecutable"
